# Handling Imbalanced Dataset

### Up sampling

Increasing the no.of samples in minority class.

### Down sampling

Reducing the no.of samples in majority class.

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Set the random seed for reproducibility
np.random.seed(123)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [3]:
n_class_0, n_class_1

(900, 100)

In [4]:
# Create My Dataframe with Imbalanced Dataset
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [5]:
df = pd.concat([class_0, class_1]).reset_index(drop=True)

In [6]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [7]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

# Method 1: Up Sampling

In [8]:
df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [9]:
from sklearn.utils import resample

In [10]:
df_minority_upsampling = resample(df_minority, replace=True, 
                                  n_samples=len(df_majority), random_state=42)

In [11]:
df_minority_upsampling

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1
..         ...        ...     ...
952   1.188902   2.189189       1
965   3.919526   1.980541       1
976   2.810326   3.604614       1
942   3.621531   2.168229       1
974   1.160887   2.489203       1

[900 rows x 3 columns]

In [12]:
df_upsampled = pd.concat([df_majority, df_minority_upsampling])

In [13]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

# Method 2: Down Sampling

In [14]:
# Create My Dataframe with Imbalanced Dataset
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [15]:
df = pd.concat([class_0, class_1]).reset_index(drop=True)

In [16]:
df.head()

   feature_1  feature_2  target
0  -1.774224   0.285744       0
1  -1.201377   0.333279       0
2   1.096257   0.531807       0
3   0.861037  -0.354766       0
4  -1.520367  -1.120815       0

In [17]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [18]:
df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [19]:
from sklearn.utils import resample

In [20]:
df_majority_downsampling = resample(df_majority, replace=True, 
                                    n_samples = len(df_minority), random_state = 42)

In [21]:
df_majority_downsampling.shape

(100, 3)

In [22]:
df_downsampled = pd.concat([df_minority, df_majority_downsampling])

In [23]:
df_downsampled['target'].value_counts()

target
1    100
0    100
Name: count, dtype: int64